---
title: "`r params$title`"
params:
  #title: "Custom Report"
  title: "Test Report"
  #technology: "Cross Flow"
  technology: "Ocean Current"
  # aoi_wkt: "POLYGON ((-67.06819 44.99416, -67.1857 44.94707, -67.21651 44.88058, -67.15834 44.78871, -67.04385 44.81789, -66.91015 44.86279, -67.06819 44.99416))"
  aoi_wkt: "POLYGON ((-68.37953 44.857, -67.38415 43.89608, -64.21114 45.0997, -64.90587 45.89335, -68.37953 44.857))"
  stressors: 
    # - Noise
    # - EMF
    - EMF
    - Lighting
  receptors:
    # - Marine Mammals
    # - Fish
    - Cetaceans
    - Pinnipeds
  stressor_receptors:
    # - Marine Mammals AND Noise
    # - Fish AND EMF
    - Bats AND Displacement
    - Cetaceans AND Noise
    - Pinnipeds AND Noise
  lit_tethys: true
  lit_ferc: false
  spatial: true
  mgt_tethys: false
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: true
    mathjax: null
  word_document:
    toc: true
    toc_depth: 4
    number_sections: true
  pdf_document:
    toc: true
    toc_depth: 4
    number_sections: true
    # keep_md: yes
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, eval = F)
```

```{r init, eval = T}
source(here::here("functions.R")) # libraries, db connection object (con)
# rmd_params <- readRDS(here("data/tmp_rmd_params.rds"))
```

# Configuration

```{r, eval = T}
# params = list(technology="Cross Flow")
tech_choices <- read_csv(here("report/data/tech_choices.csv"))
d <- tech_choices %>% 
  group_by(tech1) %>% 
  summarize(
    tech2 = paste(sort(tech2), collapse = "|"))
tech_list <- pull(d, tech2) %>% strsplit("\\|")
names(tech_list) <- pull(d, tech1)

tech <- tech_choices %>% 
  filter(tech2 == params$technology) %>% 
  mutate(
    img_local = map_chr(
      img, 
      function(url){
        # url <- tech$img
        img_local <- file.path(here("report/data/tech_images"), basename(url))
        if (!file.exists(img_local))
          download.file(url, img_local)
        img_local}))

bullets <- function(tags, indent=1){
  glue("{strrep(' ', indent*2)}- {tags}", .trim = F) %>% 
  paste(collapse = "\n") %>% 
  cat()
}
```


