---
title: project subpages (test)
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dir_scripts <<- here::here("scripts")
source(file.path(dir_scripts, "common_2.R"))
source(file.path(dir_scripts, "db.R"))
source(file.path(dir_scripts, "shiny_report.R"))
source(file.path(dir_scripts, "update.R"))


# prj_sites_csv <- here("data/project_sites.csv")

# prjs <- read_csv(here("data/project_sites.csv")) %>% 
#   mutate(
#     project_alt_name = case_when(
#       project == "Igiugig"       ~ "Iguigig",
#       project == "OPT Reedsport" ~ "REEDSPORT OPT",
#       project == "Pacwave-N"     ~ "Pacwave North",
#       project == "Pacwave-S"     ~ "Pacwave South",
#       project == "RITE"          ~ "Roosevelt Island Tidal Energy")) %>% 
#   select(prj = project, prj_alt = project_alt_name)


prjs <- dbReadTable(con, "projects") %>% 
  tibble() %>% collect() %>% 
  mutate(
    project_alt_name = case_when(
      project == "Igiugig"       ~ "Iguigig",
      project == "OPT Reedsport" ~ "REEDSPORT OPT",
      project == "Pacwave-N"     ~ "Pacwave North",
      project == "Pacwave-S"     ~ "Pacwave South",
      project == "RITE"          ~ "Roosevelt Island Tidal Energy")) %>% 
  select(prj = project, prj_alt = project_alt_name)


# prep data
match_prj <- function(
  prj_doc, prj_names = prjs$prj, alt_prj_names = prjs$prj_alt) {
    prj_index <- prj_doc %>% 
      str_detect(
        coll(
          prj_names %>%
            str_replace_all("-", " "),
          ignore_case = T)) %>% 
      unlist(recursive = T)
    if (!(TRUE %in% prj_index)) {
      prj_index <- list()
      prj_index <- prj_doc %>% 
        str_detect(
          coll(
            alt_prj_names %>%
              str_replace_all("-", " "),
            ignore_case = T)) %>% 
        unlist(recursive = T)
    }
    # get prj name that matches prj
    if (!(TRUE %in% prj_index)) {
      prj_index <- NA
    } else {
      prj_index <- which(prj_index == TRUE)
    }
    if (!(is.na(prj_index))) {
      prj_name <- prj_names[prj_index]
    } else {
      prj_name <- NA
    }
    prj_name
}







# official list of prjs and assoc'd docs/sections/etc.
prj_docs <- get_ferc() %>%
  select(prj_document, prj_doc_attachment, prj_doc_attach_url) %>% 
  distinct() %>% 
  mutate(project = map_chr(prj_document, match_prj)) %>% 
  relocate(project) %>% 
  arrange(project)


# join with projects by document
ferc_prj <- get_ferc() %>% select(-project) %>% 
  left_join(
    prj_docs %>% select(project, prj_document), 
    by = "prj_document") %>% 
  relocate(rowid, document, project)









ferc_prj_doc_sec <- ferc_prj %>% 
  select(
    prj = project, prj_doc = prj_document, 
    prj_doc_sec = prj_doc_attachment, prj_doc_sec_url = prj_doc_attach_url) %>% 
  group_by(prj, prj_doc, prj_doc_sec, prj_doc_sec_url) %>% 
  summarize()
ferc_prj_doc_sec %>% write_csv(here("data/project_doc_sec.csv"))

ferc_prj_doc <- ferc_prj_doc_sec %>% 
  group_by(prj, prj_doc) %>% 
  summarize()
ferc_prj_doc %>% write_csv(here("data/project_doc.csv"))
# View(ferc_prj)






# this also works though.
x <- get_ferc() %>% mutate(prj = map_chr(prj_document, match_prj))




# read in & merge ferc_docs & ferc_doc_tags from db
get_ferc <- function() {
  # read in ferc_docs and merge w/ table created by inner join b/w
  # ferc_doc_tags and tags lookup
  dbReadTable(con, "ferc_docs") %>% 
    tibble() %>% collect() %>% 
    na_if("NA") %>%
    merge(
      # read in ferc_doc_tags
      dbReadTable(con, "ferc_doc_tags") %>% 
        tibble() %>% collect() %>% 
        mutate(tag_sql_chr = ifelse(
          content_tag == "ALL",
          glue("{tag_category}.{content_tag}") %>% as.character(),
          tag_sql %>% as.character())) %>% 
        filter(tag_sql != "NA") %>% 
        select(-content, -tag_category, -content_tag) %>% 
        # inner_join() with tags lookup to get tag_html & tag_named
        inner_join(
          get_tags() %>% 
            mutate(
              tag_html_nocat = glue(
                "<span class='me-tag me-{cat}'>{tag_nocat}</span>")) %>% 
            select(tag_sql, tag_named, tag_html_nocat) %>% 
            rename(tag_html = tag_html_nocat),
          by = c("tag_sql_chr" = "tag_sql")) %>% 
        select(-tag_sql_chr) %>%
        group_by(rowid) %>% 
        tidyr::nest(
          tag_sql   = tag_sql,          # for UPDATING / storage
          tag_named = tag_named,        # for EDIT INTERFACE
          tag_html  = tag_html),        # for VIEW dtedit table
      # merge params
      by.x = "rowid", by.y = "rowid", all.x = T, incomparables = NA) %>% 
    mutate(
      tag_sql   = map(tag_sql,   merge_tags),
      tag_named = map(tag_named, merge_tags_named),
      tag_html  = map(tag_html,  merge_tags_html),
      document  = ifelse(
        is.na(prj_doc_attachment),
        prj_document,
        glue("{prj_document} - {prj_doc_attachment}")),
      document = ifelse(
        is.na(prj_doc_attach_url),
        document,
        glue('<a href="{prj_doc_attach_url}">{document}</a>')),
      document = as.character(document)) %>% 
    select(-project) %>% 
    mutate(project = map_chr(prj_document, match_prj)) %>% 
    relocate(
      rowid, document, project, detail, 
      tag_sql, tag_named, tag_html) %>% 
    arrange(rowid) %>%
    data.frame()
}



```


```{r}
#   prj_match <- prj_doc %>%
  #     str_extract(
  #       coll(
  #         prj_names %>%
  #           str_replace_all("-", " ") %>%
  #           str_sub(),
  #         ignore_case = T)) %>%
  #     na.omit() %>%
  #     unlist(recursive = T) %>%
  #     first()
  #   if (is.na(prj_match)) {
  #     prj_match <- prj_doc %>%
  #       str_extract(
  #         coll(
  #           alt_prj_names %>%
  #               str_replace_all("-", " ") %>%
  #               str_sub(),
  #             ignore_case = T)) %>%
  #       na.omit() %>%
  #       unlist(recursive = T) %>%
  #       first()
  #   }
  #   prj_match
  # }


prj_docs %>% slice(30) %>% match_prj

  mutate(project = map(prj_document, match_prj)) %>% 
  relocate(project) %>% 
  arrange(project)

```

```{r}

# dt table
datatable(
  prj_docs,
    options = list(
    columnDefs = list(
      list(visible = FALSE, targets = c(0, 2:4)),
      list(orderable = FALSE, className = 'details-control', targets = 1),
      list(className = 'dt-left', targets = 1:3),
      list(className = 'dt-right', targets = 4)
    )
  ),
  callback = JS("
  table.column(1).nodes().to$().css({cursor: 'pointer'});
  var format = function(d) {
    return '<div style=\"background-color:#eee; padding: .5em;\">' + 
            'Project: ' + d[1] + 
            ', Doc: ' + d[2] + 
            ', Sections: ' + d[3] + 
            ', URL: ' + d[4] + '</div>';
  };
  table.on('click', 'td.details-control', function() {
    var td = $(this), row = table.row(td.closest('tr'));
    if (row.child.isShown()) {
      row.child.hide();
      td.html('&oplus;');
    } else {
      row.child(format(row.data())).show();
      td.html('&CircleMinus;');
    }
  });"
)) 

```


